id = "rego"
name = "Rego"
version = "0.0.1"
schema_version = 1
authors = ["Styra Community <devrel@styra.com>"]
description = "Zed extension for the Rego policy language"
repository = "https://github.com/StyraInc/zed-rego"

[grammars.rego]
repository = "https://github.com/FallenAngel97/tree-sitter-rego"
commit = "9ac75e71b2d791e0aadeef68098319d86a2a14cf"

[language_servers.rego]
name = "regal"
language = "rego"
