id = "rego"
name = "Rego"
version = "0.0.2"
schema_version = 1
authors = ["Styra Community <devrel@styra.com>"]
description = "Zed extension for the Rego policy language"
repository = "https://github.com/StyraInc/zed-rego"

[grammars.rego]
repository = "https://github.com/FallenAngel97/tree-sitter-rego"
commit = "20b5a5958c837bc9f74b231022a68a594a313f6d"

[language_servers.regal]
name = "regal"
language = "rego"
